# Generated by Django 4.1 on 2022-09-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='isfinished',
            field=models.BooleanField(default=False),
        ),
    ]
